package.json

chore: 기본적인 package.json 내용 추가

---

.storybook/main.js
package.json
src/components/Button/index.stories.tsx
yarn.lock

음... 설정을 해보려고 하긴 했는데,
storybook이 6으로 버전업되면서 따로 설정해줄 것들이 많이 없어진 것 같네요 😅
일단은 기본 설정에서 필요없어보이는 config랑 디펜던시는 지워놨습니다.
그리고 필요한 addon 같은 것들이 있을까 찾아봤는데,
knobs 같이 기존에 스토리북에 자주 활용되던 애드온들이
control로 통합된 것 같습니다
찾아보면서 문제점으로 느낀게 두 가지가 있었는데요.
1. 저의 리액트와 타입스크립트 미숙함
- 이것은 좀 큰데, 샘플 스토리 작성하려고 하니까 난관이었습니다 😭
2. 스토리북의 control 옵션이랑 회의때 얘기했던 형태랑 잘 호환이 안되는 것 같음
- props로 이것저것 받아서 설정하는 형태라, 클래스만 뚫으면 활용도가 조금 떨어질 것 같다는 생각은 들었습니다.
- 이 부분 관련해서 컴포넌트 형태가 정확히 어떻게 되는지 저도 이해하지 못한 것 같다는 느낌도 들었어요
우선은 리액트랑 타입스크립트를 좀 보면서 story 관련 필요한 설정 점진적으로 추가하겠습니다.

Chore/#3 storybook 설정

---

ui-kit/src/sass/utils/_typography.scss

제곧내입니다. Line Height와 Font Size가 2배수로 변경된 것 외에 다른 변경사항은 없네요
- 디자인 시안 링크: https://www.figma.com/file/TxkDTIYPl6ygZUr5ZQ9yQ8/Lubycon-UI-Library_2?node-id=0%3A1
- 슬랙 링크: https://lubycon-hub.slack.com/archives/C01DTHQTV29/p1607269747087300
🏃‍♂️ 보통 : 최대한 빠르게 리뷰 부탁드립니다.
🙇‍♂️

feat(ui-kit): 타이포그래피 디자인 변경사항 반영

---

ui-kit/src/components/Toast/ToastBody.tsx
ui-kit/src/components/Toast/index.tsx
ui-kit/src/contexts/Toast.tsx
ui-kit/src/sass/components/_Toast.scss
ui-kit/src/stories/Toast.stories.tsx

`Toast` 컴포넌트에 align 기능을 추가합니다.
https://www.figma.com/file/TxkDTIYPl6ygZUr5ZQ9yQ8/Lubycon-UI-Library_2?node-id=0%3A1
🙇‍♂️

feat(ui-kit): 토스트에 Align 기능 추가

---

ui-kit/src/components/Button/index.tsx
ui-kit/src/components/Text/index.tsx
ui-kit/src/components/Toast/index.tsx
ui-kit/src/sass/components/_Toast.scss
ui-kit/src/stories/Toast.stories.tsx

토스트 컴포넌트의 위치 및 스타일을 수정합니다.
🙇‍♂️

feat(ui-kit): 토스트 포지션  및 스타일 수정

---

ui-kit/src/components/Switch/index.tsx
ui-kit/src/sass/components/_Switch.scss

제곧내입니다.
- `Switch` 컴포넌트의 height와 내부 패딩이 짝수 값을 가지도록 변경되었습니다.
- `Switch` 컴포넌트의 라벨이 스위치 내부 아이콘보다 살짝 밑으로 내려가있던 이슈를 수정하였습니다.
https://lubycon-hub.slack.com/archives/C01DTHQTV29/p1612672929007300
https://lubycon-hub.slack.com/archives/C01DTHQTV29/p1612673833007900
단순 스타일 변경입니다 🙇‍♂️

style(ui-kit): 수민님 디자인 피드백 반영

---

ui-kit/package.json
ui-kit/public/CNAME

`ui-kit-alpha.lubycon.io` 도메인을 사용하기 위해 `CNAME` 파일을 추가합니다.
🙇‍♂️

chore(ui-kit): 커스텀 도메인을 위한 CNAME 추가

---

ui-kit/src/components/Grid/Column.tsx
ui-kit/src/components/Grid/Row.tsx

`Row`, `Column` 컴포넌트에 커스텀 클래스 네임을 넣을 수 있도록 변경
🙇‍♂️

fix(ui-kit): Grid 컴포넌트에 클래스 넣을 수 있도록 변경

---

.github/workflows/alpha-release-docs.yml
docs/scripts/deploy.js

빌드 후 `out` 디렉토리에 `.nojekyll` 파일을 생성하고 배포하도록 변경했습니다.
🙇‍♂️

chore(docs): static resource 404 떨어지는 이슈 해결

---

lubycon-ui-kit-docs/scripts/deploy.js
ui-kit/rollup.config.js

fix(ui-kit): CSS Export 설정 변경

---

docs/src/styles/prism-theme.css

> 이 PR이 BREAKING_CHANGE를 포함하고 있다면 반드시 명시해주세요!
가현님이 수정해주신 코드 하이라이팅 스타일 적용하였습니다
- [해당 쓰레드 링크](https://lubycon-hub.slack.com/archives/C01DTHQTV29/p1618745628061600)

chore(docs): prism theme custom css

---

.releaserc.js

`fix` 커밋인데도 패치가 아니라 마이너 업데이트를 하고 있는 이슈를 수정합니다.
저희가 사용하고 있는 [commit-analyzer](https://github.com/semantic-release/commit-analyzer) 라이브러리 참고 부탁드려요!

chore(ui-kit): 시맨틱 버저닝이 제대로 되지 않는 이슈 수정 [skip ci]

---

ui-kit/src/contexts/Snackbar.tsx
ui-kit/src/stories/Snackbar.stories.tsx

> 이 PR이 BREAKING_CHANGE를 포함하고 있다면 반드시 명시해주세요!
- 스낵바 컴포넌트 스토리를 일부 수정하였습니다
- 스낵바 오픈 컨텍스트에서 id 값을 리턴하도록 하고 관련 타입 값을 변경해주었습니다
디자인 시안 링크를 첨부해주세요!
- 현재 모달 컴포넌트랑 동일하게 open 컨텍스트에서 id 값을 리턴하도록 변경하였는데, 사용하는쪽에서 작성하는 코드의 형태를 봤을때 그다지 좋은 형태가 아니라고 생각되기도 하고, 굳이 알 필요 없는 정보라는 생각도 듭니다... 🤔
- 모달은 별도로 변경할 만한게 없어서 따로 작업하지 않았습니다...! 혹시 생각하신 수정의 방향이 다르다면 말씀해주세요 ..!

스낵바 스토리 수정 + openSnackbar 컨텍스트에서 id값 리턴하도록 변경

---

ui-kit/src/stories/Components/Checkbox/Components.tsx
ui-kit/src/stories/Components/Checkbox/index.stories.mdx

> 이 PR이 BREAKING_CHANGE를 포함하고 있다면 반드시 명시해주세요!
- 체크박스 컴포넌트 docs에 controlled에 관한 설명을 추가하였습니다.
디자인 시안 링크를 첨부해주세요!

fix(ui-kit): checkbox 스토리 수정

---

ui-kit/src/components/Shadow/index.tsx
ui-kit/src/components/Spacing/index.tsx
ui-kit/src/index.ts
ui-kit/src/sass/components/_Spacing.scss
ui-kit/src/sass/components/_index.scss
ui-kit/src/stories/Components/Accordion/index.stories.mdx
ui-kit/src/stories/Components/Switch/index.stories.mdx
ui-kit/src/stories/Styles/Shadows/components.tsx
ui-kit/src/stories/Styles/Shadows/data.ts
ui-kit/src/stories/Styles/Shadows/index.stories.mdx

클래스나 짜치는 스타일로 직접 입력해서 사용해야 했던 유틸들을 컴포넌트로 작성하여 추가하였고, `Shadows` 문서 작성 완료했습니다.
```tsx
<Shadow level={1}>
<div>그림자 1단계</div>
</Shadow>
```
```tsx
<Spacing size={30} />
```
🙇‍♂️

docs: Shadow 문서 업데이트

---

src/stories/Components/List/index.stories.mdx

`List` 컴포넌트에 대한 설명을 작성합니다.
🙇‍♂️

docs: List 컴포넌트 문서 작성

---

src/utils/misc.ts

인자로 받은 루트 폰트사이즈로  pixel 값을 rem으로 변환해주는 함수를 추가했습니다!

Feat: pixel 값을 rem으로 변환해주는 함수 추가

---

.github/workflows/create-pull-request.yml

깃허브 노티피케이션 액션에 매터모스트를 추가합니다.
🙇

chore: add mattermost config to github action  [skip ci]

---

.github/workflows/alpha-storybook-publish.yml
.github/workflows/deploy-ui-kit-lib.yml
.github/workflows/live-storybook-publish.yml
src/components/Skeleton/Circle.tsx
src/components/Skeleton/Rect.tsx
src/components/Skeleton/index.tsx
src/components/Skeleton/useAnimateGradient.tsx
src/hooks/useAnimationFrame.ts
src/index.ts
src/stories/Components/Skeleton/index.stories.mdx

`Skeleton` 컴포넌트를 추가합니다.
```tsx
<div style={{ display: 'flex', flexDirection: 'column' }}>
<Skeleton width={50} height={50} type="circle" />
<Spacing size={10} />
<Skeleton width={100} height={20} />
</div>
```
🙇

feat(skeleton): Skeleton 컴포넌트 추가

---

src/components/Icon/index.tsx

이전 PR에서 피드백받았던, `Icon` 컴포넌트 내 의미없는 `style` 어트리뷰트를 제거합니다.
🙇

fix(Icon): 필요없는 style 어트리뷰트 제거

---

src/stories/Components/Grid/index.stories.mdx
src/stories/Components/Skeleton/index.stories.mdx
src/stories/Components/Spacing/index.stories.mdx

fix(docs): 영어 번역 리뷰 반영

---

src/components/Spacing/index.tsx

`display: flex`를 사용한 요소의 안 쪽이 아니더라도 `Spacing` 컴포넌트가 제대로 공간을 차지하고 간격을 표현할 수 있도록 수정합니다.
🙇

fix(Spacing): flex 안이 아니더라도 제대로 간격을 표현하도록 수정

---

src/index.ts

`Text` 키워드는 `quantumic-design`에서 유일하게 사용하는 값이 아니라서, 자동완성 시 간혹 엉뚱한 값이 들어가는 경우가 있는데, 이를 방지하기 위해 `Txt` 키워드를 추가합니다.

feat(Text): Txt alias 추가
