Lubycon/quantumic-design

.github/workflows/npm.yml

GitHub actions 에서 npm publish 용으로 많이 [사용되는 녀석](https://github.com/marketplace/actions/npm-publish)을 사용했습니다.
일단 테스트 step 같은 것은 아직 정해진 것이 없어 간단하게 Npm Registry 에 Publish 하는 것만 구현해두었습니다.

Chore/#4 Github Actions Npm publish

---

.github/workflows/publish-storybook.yml
ui-kit/src/components/Text/index.stories.tsx
ui-kit/src/components/Text/index.tsx
ui-kit/src/components/Text/types.ts
ui-kit/src/sass/utils/_typography.scss

- Text 컴포넌트의 `font-size`와 `line-height`가 변경되고, 타이포그래피 속성에서 `font-weight`가 제거되었습니다.
- Text 컴포넌트의 `fontWeight`의 default paramter로 `regular`가 지정됩니다.
- `button` 타이포그래피가 제거됩니다.
- 스토리북 배포 스크립트에서 깃 유저 없어서 찐빠나는 거 수정
- 디자인 시안 링크: https://www.figma.com/file/TxkDTIYPl6ygZUr5ZQ9yQ8/Lubycon-UI-Library_2?node-id=42%3A138
🏃‍♂️ 보통 : 최대한 빠르게 리뷰 부탁드립니다.
🙇‍♂️

feat(ui-kit): Text 컴포넌트 디자인 변경

---

ui-kit/.storybook/main.js
ui-kit/package.json
ui-kit/src/sass/utils/_index.scss
ui-kit/src/sass/utils/_shadows.scss
ui-kit/src/stories/Button.stories.tsx
ui-kit/src/stories/Shadows.stories.tsx
ui-kit/src/stories/Text.stories.tsx
yarn.lock

섀도우 스타일과 스토리북을 추가합니다. 일단은 `lubycon-shadow--{shadowLevel}` 클래스로 매핑할 수 있도록 만들어 놓았습니다. 추후 컴포넌트 단에서 어떤 식으로 사용할 지는 챕터 미팅 때 다시 한번 논의해보면 좋을 것 같아유 🙏
- 디자인 시안 링크: https://www.figma.com/file/e5zHg6E5rgkKw4v47EFXVe/Lubycon-UI-Library?node-id=0%3A1
🏃‍♂️ 보통 : 최대한 빠르게 리뷰 부탁드립니다.
`Shadow`는 컴포넌트로 구현되는 녀석이 아님에도 불구하고 스토리북이 필요합니다. 그래서 기존에 `components` 디렉토리에 종속되어있던 스토리북을 별도 디렉토리인 `stories`로 분리하였습니다.

feat(ui-kit): 섀도우 스타일, 스토리북 추가

---

ui-kit/src/components/Radio/index.tsx
ui-kit/src/sass/components/_Radio.scss
ui-kit/src/sass/components/_index.scss
ui-kit/src/stories/Radio.stories.tsx
ui-kit/src/types/utils.ts
ui-kit/src/utils/generateID.ts

Radio 컴포넌트가 추가되었습니다. 현재 `color`가 없기 때문에 일단 scss 변수로 때려넣었습니다. 추후 @Junkim93 님 작업 완료되시면 반영하겠읍니다 🙏
- 디자인 시안 링크: https://www.figma.com/file/TxkDTIYPl6ygZUr5ZQ9yQ8/Lubycon-UI-Library_2?node-id=0%3A1
🏃‍♂️ 보통 : 최대한 빠르게 리뷰 부탁드립니다.
`generateID` 함수를 헤비하게 짤 필요가 없는 것 같아서 그냥 모듈 스코프에서 `number` 값을 1씩 증가시키는 것으로 해결했는데, 이거 해싱을 쓰는게 나을까요...?

feat(ui-kit): Radio 컴포넌트 추가

---

ui-kit/src/components/Radio/index.tsx
ui-kit/src/sass/components/_Checkbox.scss
ui-kit/src/sass/components/_Radio.scss
ui-kit/src/sass/components/_Switch.scss
ui-kit/src/sass/utils/_colors.scss

- `Radio` 컴포넌트의 라디오 아이콘 부분을 클릭하면 선택이 되지 않던 버그를 수정합니다.
- `Radio` 컴포넌트의 Primary 컬러가 파란색으로 되어있던 부분을 UI Kit 컬러 팔레트의 `green50`으로 변경합니다.
- SCSS 내에서 `map-get($colors, $name)`으로 컬러를 가져오던 부분을 `get-color($name)` 함수를 통해 가져오도록 변경합니다.
🙇‍♂️

style(ui-kit): Radio 컴포넌트의 색을 green50으로 변경

---

ui-kit/package.json
ui-kit/src/components/Checkbox/index.tsx
ui-kit/src/components/Container/index.tsx
ui-kit/src/components/Container/style.scss
ui-kit/src/components/Grid/Column.tsx
ui-kit/src/components/Grid/Row.tsx
ui-kit/src/components/Icon/index.tsx
ui-kit/src/components/Radio/index.tsx
ui-kit/src/components/Selection/index.tsx
ui-kit/src/components/Switch/index.tsx
ui-kit/src/components/Text/index.tsx
ui-kit/src/components/index.ts
ui-kit/src/sass/components/_Icon.scss
ui-kit/src/sass/components/_Selection.scss
ui-kit/src/sass/components/_index.scss
ui-kit/src/stories/Selection.stories.tsx
yarn.lock

Selection 컴포넌트를 추가합니다. Option 엘리먼트트의 UI는 디자인 챕터와 논의해서 일단은 네이티브 UI를 그대로 사용하기로 의사결정했습니다. 그래서 Select 태그 쪽만 스타일링 되어있음
- UI Kit 내 아이콘 사용을 위해 `ionicons` 라이브러리 추가
- `Icon` 컴포넌트 추가 (관련 대화: https://lubycon-hub.slack.com/archives/C01E919MTBM/p1609598708142600)
🙇‍♂️

feat(ui-kit): Selection 컴포넌트 추가

---

ui-kit/src/components/LubyconUIKitProvider/index.tsx
ui-kit/src/components/Snackbar/SnackbarBody.tsx
ui-kit/src/components/Snackbar/index.tsx
ui-kit/src/components/index.ts
ui-kit/src/contexts/Snackbar.tsx
ui-kit/src/sass/components/_Button.scss
ui-kit/src/sass/components/_Snackbar.scss
ui-kit/src/sass/components/_index.scss
ui-kit/src/stories/Snackbar.stories.tsx
ui-kit/src/stories/Toast.stories.tsx

대부분 토스트 컴포넌트의 복붙입니다. 추상화는 TO DO로 가져가겠슴다.
- `Snackbar` 컴포넌트 추가
- `SnackbarContext` 추가
- `Button` 컴포넌트의 `height` 속성 제거 (`line-height` 가 안 맞아서 버튼이 비뚤게 보임. 디챕과 협의해야함)
```jsx
<Snackbar show={true} message="하이호이 테스트입니다" button="실행취소" onClick={() => {}} />
<Snackbar
show={true}
message="하이호이 테스트입니다"
button={
<>
<Button onClick={() => alert('실행 취소 완료')}>실행취소</Button>
<Button onClick={() => alert('메세지 보기 클릭')}>메세지 보기</Button>
</>
}
/>
```
싱글 버튼과 멀티버튼은 이런 식으로 사용할 수 있습니다. `button` 프로퍼티에 원시형 타입가 아닌 타입이 들어올 경우 `onClick: never`로 정의하려고 했는데, 요것도 일단 TO DO로....ㅎㅎ 도전해보고 싶으신 분 있으시면 해보시면 좋을 것 같습니다.
```ts
const { openSnackbar } = useSnackbar();
openSnackbar({
message: '하이호이 테스트입니다',
button: '실행취소',
onClick: handleSnackbarClick
});
```
https://www.figma.com/file/e5zHg6E5rgkKw4v47EFXVe/Lubycon-UI-Library?node-id= …

feat(ui-kit): 스낵바 컴포넌트 추가

---

.eslintrc.js
ui-kit/src/components/Card/CardContent.tsx
ui-kit/src/components/Card/CardFooter.tsx
ui-kit/src/components/Card/CardHeader.tsx
ui-kit/src/components/Card/CardImageContent.tsx
ui-kit/src/components/Card/index.tsx
ui-kit/src/components/index.ts
ui-kit/src/sass/components/_Card.scss
ui-kit/src/sass/components/_index.scss
ui-kit/src/sass/utils/_colors.scss
ui-kit/src/stories/Card.stories.tsx

카드 컴포넌트를 추가합니다.
https://www.figma.com/file/e5zHg6E5rgkKw4v47EFXVe/Lubycon-UI-Library
`Card.Header` 처럼 스태틱 멤버로 export 하고 싶었는데 `ForwardRefExoticComponent` 타입에는 스태틱 멤버를 넣기가 쉽지가 않네유...혹시 좋은 타이핑 아이디어 있으시면 코멘트 부탁드립니다!

feat(ui-kit): 카드 컴포넌트 추가

---

ui-kit/src/components/Input/index.tsx
ui-kit/src/index.ts
ui-kit/src/sass/components/_Input.scss
ui-kit/src/sass/components/_index.scss
ui-kit/src/stories/Input.stories.tsx

`Input` 컴포넌트를 추가합니다. 기본적으로 `input` 엘리먼트의 인터페이스를 확장하되, `type`을 텍스트 입력과 관련된 타입만 받을 수 있도록 제한합니다.
```ts
type TextInputType = 'text' | 'tel' | 'url' | 'email' | 'number' | 'password' | 'search';
```
```tsx
<Input
style={{ width: 300 }}
label="라벨이에요"
placeholder="텍스트를 입력하세요"
hasError={isError}
description={isError ? '빈 문자열은 허용되지 않습니다' : undefined}
onChange={(e) => setValue(e.target.value)}
right={
isError ? null : (
<Icon icon={checkmarkCircle} type="filled" color={colors.green50} size={20} />
)
}
/>
```
🙇‍♂️

feat(ui-kit): Input 컴포넌트 추가

---

ui-kit/package.json
ui-kit/src/components/Accordion/index.tsx
ui-kit/src/hooks/useResizeObserver.ts
ui-kit/src/index.ts
ui-kit/src/sass/components/_Accordion.scss
ui-kit/src/sass/components/_Input.scss
ui-kit/src/sass/components/_index.scss
ui-kit/src/stories/Accordion.stories.tsx
yarn.lock

1. `Accordion` 컴포넌트가 추가되었습니다.
2. `ref`로 받은 엘리먼트의 리사이징 이벤트를 감시하는 `useResizeObserver` 훅이 추가되었습니다.
3. `Input` 컴포넌트의 focused 상태 스타일이 변경되었습니다. [관련 슬랙 대화](https://lubycon-hub.slack.com/archives/C017ZLLFSSX/p1613468270014300?thread_ts=1613398168.004700&cid=C017ZLLFSSX)
```tsx
<Accordion label="👀 텍스트가 숨겨져 있어요">
아코디언이 펼쳐지면 아래에 내용이 나옵니다.
<br />
아코디언이 펼쳐지면 아래에 내용이 나옵니다.
<br />
아코디언이 펼쳐지면 아래에 내용이 나옵니다.
<br />
</Accordion>
```
라벨은 `ReactNode` 타입으로 하려다가, 아이콘 부분까지 자유롭게 열어줄게 아니라면 크게 의미가 없겠다 싶어서 `string`타입을 받도록 설계했슴다.
또한 각각의 아코디언 컴포넌트는 독립적인 상태를 가지므로 Uncontrolled 컴포넌트로 만들어서 사용자가 직접 불필요한 상태 관리를 하지 않는 방향으로 설계했슴다.
https://www.figma.com/file/e5zHg6E5rgkKw4v47EFXVe/Lubycon-UI-Library?node-id=775%3A388
🙇‍♂️

feat(ui-kit): Accordion 컴포넌트 추가

---

ui-kit/src/components/ProgressBar/index.tsx
ui-kit/src/index.ts
ui-kit/src/sass/components/_ProgressBar.scss
ui-kit/src/sass/components/_index.scss
ui-kit/src/stories/ProgressBar.stories.tsx

`ProgressBar` 컴포넌트를 추가합니다.
```tsx
<ProgressBar
value={50}
max={100}
showLabel={true}
labelPosition="bottom"
labelFormatter={(value) => `현재 값은 ${value}입니다`}
/>
```
https://www.figma.com/file/e5zHg6E5rgkKw4v47EFXVe/Lubycon-UI-Library?node-id=791%3A0
🙇‍♂️

feat(ui-kit): ProgressBar 컴포넌트 추가

---

ui-kit/src/components/Accordion/index.tsx
ui-kit/src/components/Alert/index.tsx
ui-kit/src/components/Button/index.tsx
ui-kit/src/components/Card/CardImageContent.tsx
ui-kit/src/components/Input/index.tsx
ui-kit/src/components/List/ListItem.tsx
ui-kit/src/components/Snackbar/SnackbarBody.tsx
ui-kit/src/components/Snackbar/index.tsx
ui-kit/src/sass/components/_Button.scss
ui-kit/src/stories/Button.stories.tsx
ui-kit/src/stories/Toast.stories.tsx
ui-kit/src/stories/Tooltip.stories.tsx

1. `Button` 컴포넌트의 기본 색상이 투명으로 변경되었습니다.
2. `Button` 컴포넌트의 `type` 프로퍼티가 추가되었습니다. HTML5의 `type` 속성은 `htmlType` 프로퍼티가 대체합니다.
3. `CombineElementProps` 타입을 사용해도 되는 부분에 `Combine` 타입이 사용되고 있던 부분들을 수정합니다.
https://www.figma.com/file/e5zHg6E5rgkKw4v47EFXVe/Lubycon-UI-Library?node-id=775%3A78
🙇‍♂️

feat(ui-kit): Button 컴포넌트 타입 추가

---

ui-kit/src/components/Modal/index.tsx
ui-kit/src/components/Table/TableCell.tsx
ui-kit/src/components/Table/TableHead.tsx
ui-kit/src/components/Table/TableRow.tsx
ui-kit/src/contexts/Modal.tsx
ui-kit/src/sass/components/_Modal.scss
ui-kit/src/stories/Modal.stories.tsx
ui-kit/src/stories/Table.stories.tsx

`Modal` 컴포넌트에 애니메이션을 추가합니다.
~~`useModal`의 `closeModal` 사용 시 모달 스택 배열에서 바로 모달 상태가 제거되면서 애니메이션이 실행되지 않고 바로 모달이 사라지는 이슈가 있습니다. 애니메이션 끝난 다음에 스택 배열에서 모달 상태를 제거해야하는데, 일단 아이디어가 안 떠올라서 그냥 고고 했습니당~~
요거 해결했슴당 ㅎㅎ

feat(ui-kit): Modal 컴포넌트 애니메이션 추가

---

ui-kit/src/sass/components/_Row.scss

`Row` 컴포넌트에 의도치 않은 상하 마진이 포함되어 이를 제거합니다

fix(ui-kit): Row 컴포넌트 상하 마진 제거

---

.github/CODEOWNERS
.github/workflows/alpha-release-docs.yml
docs/gatsby-hooks/createPages.js
docs/src/content/testPage.mdx
docs/src/templates/page.tsx
ui-kit/src/components/Button/index.tsx

> CODEOWNERS 테스트를 위해 다시 엽니다
- Docs에 이전, 다음 컨텐츠로 이동할 수 있는 버튼을 추가합니다.
- `Button` 컴포넌트가 Custom한 `className`을 Props로 받을 수 있도록 변경합니다.
🙇‍♂️

feat(docs): Docs에 Prev, Next 버튼 추가

---

.github/workflows/create-pull-request.yml
.releaserc.js
ui-kit/src/components/Card/CardContent.tsx
ui-kit/src/components/Card/CardFooter.tsx
ui-kit/src/components/Card/CardHeader.tsx
ui-kit/src/components/Card/index.tsx
ui-kit/src/components/Checkbox/index.tsx
ui-kit/src/components/Modal/ModalContent.tsx
ui-kit/src/components/Modal/ModalFooter.tsx
ui-kit/src/components/Modal/ModalHeader.tsx
ui-kit/src/components/Modal/ModalWindow.tsx
ui-kit/src/components/Modal/index.tsx
ui-kit/src/components/Radio/index.tsx
ui-kit/src/components/Selection/index.tsx
ui-kit/src/components/Switch/index.tsx
ui-kit/src/components/Table/TableBody.tsx
ui-kit/src/components/Table/TableCell.tsx
ui-kit/src/components/Table/TableHead.tsx
ui-kit/src/components/Table/TableRow.tsx
ui-kit/src/components/Table/index.tsx
ui-kit/src/components/Table/props.ts
ui-kit/src/components/Tooltip/TooltipBody.tsx
ui-kit/src/components/Tooltip/index.tsx

- 모든 컴포넌트들이 HTMLAttributes를 상속받도록 변경하고, `className` 과 `...props` 를 컴포넌트에 주입받습니다.
- Emotion, Tailwind CSS와 같이 CSS 클래스 기반으로 작동하는 녀석들을 함께 사용하기 위함.
- 
- 슬랙 노티를 주는 깃헙 액션을 추가하였습니다. [노션 문서](https://www.notion.so/lubycon/PR-8f5fe3ff8f0e4d7d8c77ab5a0fed2238)를 참고해주세요!
전부 `className` 과 `props`를 주입하는 변경사항이기는 한데, `Table` 컴포넌트 같은 경우는 프로퍼티 타입 정의도 조금 바꿨습니다. 요 부분 신경써서 봐주시면 좋을 듯!

feat(ui-kit): 모든 컴포넌트가 HTML 엘리먼트를 상속받도록 수정

---

ui-kit/src/components/Icon/index.tsx
ui-kit/src/components/Icon/utils.ts
ui-kit/src/stories/Components/Icons/index.stories.mdx

- 아이콘의 이름이 `logo-`로 시작하는 경우에는 무조건 타입을 `filled`로 지정합니다. (다른 타입이 없음 ㅜ)
- 다만 `Icon` 컴포넌트의 `apple-logo-ar`인 경우에는 `outline`으로 지정합니다.
- `Icon` 컴포넌트 문서 내용 추가
🙇‍♂️

fix(ui-kit): apple-logo-ar 아이콘의 경우에는 무조건 outline으로 타입이 지정되도록 수정

---

.github/workflows/alpha-storybook-publish.yml
.github/workflows/deploy-ui-kit-lib.yml
.github/workflows/live-storybook-publish.yml
src/components/Tabs/TabsItem.tsx

- pnpify를 설치하여 IDE에서 typescript 모듈을 찾지 못하는 이슈를 수정합니다
- CI/CD 트리거가 `master` 브랜치에 잡혀있는 것을 `main`으로 변경합니다.
🙇‍♂️

fix: vscode에서 typescript 모듈을 찾지 못하는 이슈 수정 [skip ci]

---

.github/workflows/create-pull-request.yml

매터모스트로 PR 노티를 줄 수 있도록 notifier의 버전을 `2.0.0`으로 업데이트 합니다.
🙇

chore: github notifier 버전을 2.0.0으로 업데이트 [skip ci]

---

src/hooks/useScroll.ts

ref 로 넘겨준 엘리먼트에 scroll 이벤트를 추가할 수있는 hook을 만들었습니다.
- 사용법
```javascript
const Test = () => {
const refEl = useRef<HTMLDivElement>(null);
const handleScroll = () => {
console.log("scrollin' rollin' rollin'");
};
useScroll(refEl, handleScroll);
return (
<div
ref={refEl}
style={{ width: "14px", height: "10px", overflow: "auto" }}
>
후후후후후후후후
</div>
);
};
```

Feat: useScroll 훅 추가

---

src/components/Flex/index.tsx
src/index.ts
src/stories/Components/ProgressBar/ProgressBar.tsx
src/stories/Components/Skeleton/index.stories.mdx
src/stories/Styles/Shadows/components.tsx
src/stories/Styles/Typography/index.stories.mdx
src/types/utils.ts

- `display: flex` 를 추상화한 `Flex` 컴포넌트를 추가합니다.
- 기존에 `ref` 프로퍼티가 없는 것으로 평가되던 `OvverridableProps` 타입이 제대로 `ref`까지 추적하도록 수정합니다.
```tsx
<div css={{.display: 'flex', alignItems: 'center', justifyContent: "center'  }}></div>
```
```tsx
<Flex align="center" justify="center"></Flex>
```
🙇

feat: Flex 컴포넌트 추가

---

.github/workflows/create-pull-request.yml
src/components/Flex/index.tsx
src/components/Grid/Column.tsx
src/components/Text/index.tsx

`Flex` 컴포넌트가 `as` Props는 받고 있는데 쓰지를 않고 있었네요. 이 값을 이용하여 `Flex` 를 사용할 때 원하는 컴포넌트로 렌더할 수 있게끔 변경합니다.
🙇

feat(Flex): flex 컴포넌트를 원하는 컴포넌트로 렌더할 수 있도록 수정

---

src/contexts/Overlay/OverlayContext.tsx
src/stories/Hooks/useOverlay/components.tsx
src/stories/Hooks/useOverlay/index.stories.mdx

`OverlayContext` 내부에 있는 `value`의 메모아이제이션 기준으로 브라우저 API인 `open`, `close`가 포함되어 있는 버그를 수정합니다.
🙇

fix(overlay): 브라우저 API가 디펜던시 어레이에 들어가 있는 이슈 수정

---

src/contexts/Overlay/StateReacter.tsx
src/contexts/Overlay/useOverlay.tsx
src/stories/Hooks/useOverlay/components.tsx
src/stories/Hooks/useOverlay/index.stories.mdx

`useOverlay`를 사용할 때 매번 `useEffect` 훅 내에서 `createOverlayElement`를 사용하는 방식을 개선하여, `open` 함수만으로 오버레이를 사용할 수 있도록 변경합니다.
```tsx
const { open } = useOverlay();
return (
<button
onClick={() => {
open(({ isOpen, close }) => {
return (
<div style={{ display: isOpen ? 'block' : 'none' }}>
모달입니다.
<button onClick={close}>닫기</button>
</div>
);
});
}}
>
모달 열기
</button>
);
```
```tsx
const { open } = useOverlay();
const openModal = () => {
return new Promise<void>((resolve) => {
open(({ isOpen, close }) => {
return (
<div style={{ display: isOpen ? 'block' : 'none' }}>
모달입니다.
<button
onClick={() => {
close();
resolve();
}}
>
닫기
</button>
</div>
);
});
});
};
return (
<button
onClick={async () => {
await openModal();
alert('모달 닫힘');
}}
>
모달 열기
</button>
);
```
🙇

feat(useOverlay): createOverlayElement 없이도 overlay를 사용할 수 있도록 수정
